"""DEFAULT, IDENTITY and PRIMARY KEY are not carried because AIDP REFUSES
them -- and the plan now says that, instead of "unverified".

The old wording said nothing offline confirmed the catalog accepts a column
default or an identity, so they were held back as a precaution. Probe 1
(live 2026-09-29, AIDP Spark 3.5.0 / Delta 3.1.0) settled it the other way:

  * `CREATE TABLE ... (v STRING DEFAULT 'x') USING DELTA` ->
    `[UNSUPPORTED_FEATURE.TABLE_OPERATION] ... does not support column
    default value`.
  * `id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY
    1)` and `GENERATED ALWAYS AS IDENTITY` -> `[PARSE_SYNTAX_ERROR]`.
  * `CONSTRAINT t_pk PRIMARY KEY (id)` -> `[PARSE_SYNTAX_ERROR]`.
  * NOT NULL and CHECK constraints ARE enforced.

So the sentence an operator reads must be the refusal, with its date --
"unverified" invites someone to try it, and the target will just say no.
The source shape is the trial's T_DEFAULTS: ID `IDENTITY START 1 INCREMENT 1
NOORDER`, STATUS `DEFAULT 'NEW'`.
"""
from target.ddl import build_create_table, uncarried_column_facts


def _col(name, pos, *, default=None, start=None, step=None):
    return {"COLUMN_NAME": name, "DATA_TYPE": "NUMBER" if name != "STATUS"
            else "TEXT", "ORDINAL_POSITION": pos, "IS_NULLABLE": "YES",
            "target_type": "DECIMAL(38,0)" if name != "STATUS" else "STRING",
            "NUMERIC_PRECISION": 38, "NUMERIC_SCALE": 0,
            "COLUMN_DEFAULT": default, "IDENTITY_START": start,
            "IDENTITY_INCREMENT": step, "COMMENT": None}


def _t_defaults(**over):
    rec = {"source_identifier": "SNOWMIG_COVERAGE.TYPES.T_DEFAULTS",
           "object_type": "TABLE", "compatibility_status": "supported",
           "source_metadata": {},
           "columns": [_col("ID", 1, start="1", step="1"),
                       _col("STATUS", 2, default="'NEW'"),
                       _col("N", 3)]}
    rec.update(over)
    return rec


def _rules(res, rule_id):
    return [r for r in res.rules_applied if r.rule_id == rule_id]


def test_the_default_warning_cites_the_live_refusal():
    res = build_create_table(_t_defaults(), "cat.types.t_defaults")
    warning = next(w for w in res.warnings if w.startswith("STATUS:"))
    assert "does not support column default value" in warning
    assert "2026-09-29" in warning
    assert "nothing offline confirms" not in warning


def test_the_identity_warning_cites_the_live_refusal():
    res = build_create_table(_t_defaults(), "cat.types.t_defaults")
    warning = next(w for w in res.warnings if w.startswith("ID:"))
    assert "PARSE_SYNTAX_ERROR" in warning and "2026-09-29" in warning
    assert "unverified" not in warning


def test_each_rule_is_recorded_once_and_cites_the_refusal():
    # The rules were appended twice, with two different wordings.
    res = build_create_table(_t_defaults(), "cat.types.t_defaults")
    r22 = _rules(res, "R22_COLUMN_DEFAULT_NOT_EMITTED")
    r23 = _rules(res, "R23_IDENTITY_NOT_EMITTED")
    assert len(r22) == 1 and len(r23) == 1
    assert "does not support column default value" in r22[0].detail
    assert "PARSE_SYNTAX_ERROR" in r23[0].detail
    assert len(res.warnings) == len(set(res.warnings))


def test_a_primary_key_is_named_as_refused_by_the_target():
    res = build_create_table(
        _t_defaults(constraints=[{"constraint_type": "PRIMARY KEY",
                                  "name": "PK_T", "columns": ["ID"]}]),
        "cat.types.t_defaults")
    rule = _rules(res, "R20_CONSTRAINTS_NOT_EMITTED")[0]
    assert "PRIMARY KEY (ID)" in rule.detail
    assert "PARSE_SYNTAX_ERROR" in rule.detail
    # What Delta does enforce is said too: NOT NULL and CHECK.
    assert "NOT NULL" in rule.detail and "CHECK" in rule.detail


def test_the_plan_entry_reads_the_same_sentence():
    # PLANNED_OBJECTS.md and DDL_PLAN.md share uncarried_column_facts.
    facts = uncarried_column_facts(_t_defaults())
    assert any("does not support column default value" in f for f in facts)
    assert any("PARSE_SYNTAX_ERROR" in f for f in facts)


def test_nothing_refused_is_emitted():
    res = build_create_table(_t_defaults(), "cat.types.t_defaults")
    up = res.sql.upper()
    assert " DEFAULT " not in up and "IDENTITY" not in up
    assert "PRIMARY KEY" not in up
