#!/usr/bin/env python3
"""Put the bundled demo's sample data on AIDP, so its job can run end to end.

The demo migrates a synthetic estate. Its translated job reads files a real
Fabric workspace would hold -- `SalesLake.Lakehouse/Files/raw/claims` -- and
a warehouse table, `AcmeDW.claim`, that a real migration would have loaded.
Neither exists on a fresh AIDP account, so the job fails at its first read:

    BucketNotFound: Either the bucket named 'AcmeWS_SalesLake_Lakehouse' does
    not exist in the namespace '<namespace>' ...

That is the input, not the translation. This script supplies it, and reads
everything it needs from the migration's own output so it cannot drift from
what the tool emitted:

* the bucket and path, from the migrated ingest notebook's `oci://` URI;
* the schemas, from `setup/catalogs.sql` (run again; every statement is
  IF NOT EXISTS);
* `AcmeDW.claim`, by running the migrated `warehouse/dbo.claim.spark.sql`
  itself -- so the seed is also a real run of one of the tool's warehouse
  scripts on AIDP.

The data is 20 claim rows over 4 policies (`claim_id, policy_no, amount,
opened`): the shape that made the published job run green on AIDP when it was
seeded by hand, 2026-09-30.

Existing data is KEPT unless --overwrite. Learned the hard way: the first live
run found the demo bucket already there -- created a day earlier by a
colleague seeding by hand -- and overwrote her files at the same path, because
the seed wrote in overwrite mode and the existence check had looked in the
wrong namespace. A seed that silently replaces someone's data is not a demo
helper. Now: if the path already holds rows, or the table already exists,
they are reported and left alone.

It is generated by Spark on the cluster, so this script needs nothing beyond
the `aidp` CLI that `publish` already uses (and the `oci` CLI only with
--create-bucket). It is a demo helper, not part of the migration: a real
estate's data has to be moved by whatever moves data, which this tool does not.

    python scripts/seed_demo_data.py out/migrated \\
        --workspace-key <key> --cluster-key <uuid> --profile <p> --auth api_key \\
        [--create-bucket --compartment <compartment-ocid>] [--dry-run]

Run it after `publish --apply` and before running the job.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

INGEST_NOTEBOOK = "notebooks/01_Ingest_Claims.py"
CLAIM_DDL = "warehouse/dbo.claim.spark.sql"
SETUP_SQL = "setup/catalogs.sql"
SEED_NOTEBOOK = "zz_seed_demo_data.ipynb"
_URI_RE = re.compile(r"oci://(?P<bucket>[^@/\s\"']+)@(?P<ns>[^/\s\"']+)(?P<path>/[^\s\"')]*)")
_TABLE_RE = re.compile(r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?P<name>[^\s(]+)",
                       re.IGNORECASE)
POLICIES = ("P1", "P2", "P3", "P4")
ROWS = 20
FINAL = {"SUCCESS", "FAILED", "UPSTREAM_FAILED", "CANCELED", "SKIPPED",
         "TIMEDOUT", "INTERNAL_ERROR"}


class SeedError(Exception):
    pass


def _statements(sql: str) -> list:
    """`;`-separated statements, comment lines dropped."""
    body = "\n".join(line for line in sql.splitlines()
                     if not line.lstrip().startswith("--"))
    return [s.strip() for s in body.split(";") if s.strip()]


def read_inputs(migrated) -> dict:
    """What the seed needs, read off a migration's output, or SeedError."""
    migrated = Path(migrated)
    ingest = migrated / INGEST_NOTEBOOK
    ddl = migrated / CLAIM_DDL
    for path in (ingest, ddl):
        if not path.is_file():
            raise SeedError(
                f"{path} not found: this seeds the bundled demo, so point it at "
                f"`migrate` output for the demo estate (make demo, or "
                f"fixtures/demo-workspace)")
    found = _URI_RE.search(ingest.read_text(encoding="utf-8"))
    if not found:
        raise SeedError(
            f"no oci:// URI in {ingest}: was the plan built with --namespace? "
            f"Without one the path keeps a placeholder and has no bucket")
    statements = _statements(ddl.read_text(encoding="utf-8"))
    create = next((s for s in statements if _TABLE_RE.match(s)), None)
    if create is None:
        raise SeedError(f"no CREATE TABLE in {ddl}")
    setup = migrated / SETUP_SQL
    return {
        "uri": found.group(0),
        "bucket": found.group("bucket"),
        "namespace": found.group("ns"),
        "claim_table": _TABLE_RE.match(create).group("name"),
        "claim_ddl": create,
        "setup": _statements(setup.read_text(encoding="utf-8")) if setup.is_file() else [],
    }


def seed_rows():
    """20 claims over 4 policies, deterministic: (claim_id, policy, amount, day)."""
    return [(i, POLICIES[(i - 1) % len(POLICIES)], round(100.0 + 12.5 * i, 2),
             f"2026-09-{(i - 1) % 28 + 1:02d}")
            for i in range(1, ROWS + 1)]


def seed_notebook(inputs, overwrite=False) -> str:
    """The seed notebook as .ipynb text.

    With `overwrite` False (the default) existing files at the path and an
    existing claim table are kept and reported; only what is missing is
    written.
    """
    rows = seed_rows()
    claim_values = ", ".join(
        f"({cid}, '{pol}', TIMESTAMP'{day} 00:00:00', {'true' if cid % 3 else 'false'})"
        for cid, pol, _, day in rows)
    cells = [
        "# Generated by scripts/seed_demo_data.py: sample data for the demo.\n"
        "# 1. The schemas, from the migration's own setup/catalogs.sql.\n"
        f"for statement in {inputs['setup']!r}:\n"
        "    spark.sql(statement)\n",
        "# 2. The files the migrated ingest notebook reads.\n"
        f"OVERWRITE = {overwrite!r}\n"
        "def _rows_at(uri):\n"
        "    try:\n"
        "        return spark.read.parquet(uri).count()\n"
        "    except Exception:\n"
        "        return 0\n"
        "from pyspark.sql import Row\n"
        "from datetime import datetime\n"
        f"rows = {rows!r}\n"
        "df = spark.createDataFrame([Row(claim_id=c, policy_no=p, amount=a,\n"
        "                                opened=datetime.strptime(d, '%Y-%m-%d'))\n"
        "                            for c, p, a, d in rows])\n"
        f"existing = _rows_at({inputs['uri']!r})\n"
        "if existing and not OVERWRITE:\n"
        f"    print('kept', existing, 'existing rows at', {inputs['uri']!r}, '(pass --overwrite to replace)')\n"
        "else:\n"
        f"    df.write.mode('overwrite').parquet({inputs['uri']!r})\n"
        f"    print('wrote', spark.read.parquet({inputs['uri']!r}).count(), 'rows to', {inputs['uri']!r})\n",
        "# 3. The warehouse table, by the migrated DDL itself, then rows.\n"
        f"exists = spark.catalog.tableExists({inputs['claim_table']!r})\n"
        "if exists and not OVERWRITE:\n"
        f"    print('kept existing table {inputs['claim_table']} (pass --overwrite to replace)')\n"
        "else:\n"
        f"    spark.sql({('DROP TABLE IF EXISTS ' + inputs['claim_table'])!r})\n"
        f"    spark.sql({inputs['claim_ddl']!r})\n"
        f"    spark.sql({('INSERT INTO ' + inputs['claim_table'] + ' VALUES ' + claim_values)!r})\n"
        f"print('{inputs['claim_table']}:', spark.table({inputs['claim_table']!r}).count(), 'rows')\n",
    ]
    return json.dumps({
        "nbformat": 4, "nbformat_minor": 5,
        "metadata": {"kernelspec": {"name": "python3", "display_name": "Python 3",
                                    "language": "python"},
                     "language_info": {"name": "python"}},
        "cells": [{"cell_type": "code", "execution_count": None, "metadata": {},
                   "outputs": [], "source": cell} for cell in cells]})


def readable_failure(output_text: str) -> str:
    """The error text in a task's output, or "" when it holds none.

    Reported in review: after a failed task the raw output was printed, and
    when the task never started it is all nulls -- `{"key": null, "taskType":
    "NOTEBOOK_TASK", ..., "errorTrace": null, "data": null, ...}` -- a line
    that says nothing. Now only real error text is shown: an `errorTrace`, or
    a notebook cell's `ename`/`evalue`/`traceback`.
    """
    try:
        payload = json.loads(output_text)
    except (TypeError, ValueError):
        return ""
    found = []

    def walk(node):
        if isinstance(node, dict):
            for key, value in node.items():
                if key in ("errorTrace", "ename", "evalue") and isinstance(value, str) and value.strip():
                    found.append(value.strip())
                elif key == "traceback" and isinstance(value, list):
                    found.append("\n".join(str(v) for v in value))
                else:
                    walk(value)
        elif isinstance(node, list):
            for value in node:
                walk(value)
        elif isinstance(node, str) and node.lstrip().startswith(("{", "[")):
            try:
                walk(json.loads(node))
            except ValueError:
                pass

    walk(payload)
    return "\n".join(found)


def create_bucket(inputs, compartment, profile=None, auth=None) -> str:
    """The empty bucket, via the `oci` CLI; "created" or "exists"."""
    oci = shutil.which("oci")
    if oci is None:
        raise SeedError("--create-bucket needs the `oci` CLI on PATH")
    base = [oci, "os", "bucket"]
    extra = (["--profile", profile] if profile else []) + (
        ["--auth", auth] if auth and auth != "api_key" else [])
    got = subprocess.run(base + ["get", "--namespace", inputs["namespace"],
                                 "--bucket-name", inputs["bucket"]] + extra,
                         capture_output=True, text=True)
    if got.returncode == 0:
        return "exists"
    made = subprocess.run(base + ["create", "--namespace", inputs["namespace"],
                                  "--name", inputs["bucket"],
                                  "--compartment-id", compartment] + extra,
                          capture_output=True, text=True)
    if made.returncode != 0:
        raise SeedError(f"oci os bucket create failed: {made.stderr.strip()[:400]}")
    return "created"


def run_seed(inputs, args) -> int:
    from fabric_aidp.publish.aidp_client import AidpClient
    client = AidpClient(workspace_key=args.workspace_key, instance_id=args.instance_id,
                        profile=args.profile, auth=args.auth)
    root = args.workspace_root.rstrip("/")
    path = f"{root}/{args.prefix}/{SEED_NOTEBOOK}" if args.prefix else f"{root}/{SEED_NOTEBOOK}"
    problem = client.cluster_problem(args.cluster_key)
    if problem:
        raise SeedError(problem)
    client.put_notebook(path, seed_notebook(inputs, overwrite=args.overwrite))
    print(f"uploaded {path}")
    name = f"{args.prefix + '_' if args.prefix else ''}seed_demo_data"
    # Reused when it already exists. Reported in review: a run that stopped
    # after creating its job could not be repeated -- the next create-job was
    # refused with JOB_VALIDATE_0031, the name being taken. The notebook it
    # runs was just re-uploaded to the same path, so reusing the job runs the
    # new content; a unique name per run would instead leave one stale job
    # behind every time.
    definition = {
        "name": name, "maxConcurrentRuns": 1,
        "tasks": [{"type": "NOTEBOOK_TASK", "taskKey": "seed", "runIf": "ALL_SUCCESS",
                   "maxRetries": 0, "notebookPath": path, "source": "WORKSPACE",
                   "timeoutSeconds": 1800,
                   "cluster": {"clusterKey": args.cluster_key}}]}
    job = next((j.get("key") for j in client.list_jobs()
                if j.get("name") == name and j.get("key")), None)
    if job:
        # A reused job keeps the cluster it was created with, so a re-run with
        # a different --cluster-key ran on the old one (found in review). The
        # job is brought back in line with this run's arguments when it
        # differs, and left untouched when it does not.
        tasks = client.get_job(job).get("tasks") or [{}]
        current = (((tasks[0] or {}).get("cluster") or {}).get("clusterKey"),
                   (tasks[0] or {}).get("notebookPath"))
        if current != (args.cluster_key, path):
            client.update_job(job, definition)
            print(f"reusing job {name} ({job}), updated to cluster {args.cluster_key} "
                  f"(was {current[0]})")
        else:
            print(f"reusing job {name} ({job}) from an earlier run")
    else:
        job = client.create_job(definition)
        print(f"created job {name} ({job})")
    run = client.run_job(job)
    print(f"started run {run}")
    for _ in range(int(args.wait / 15) + 1):
        tasks = client.task_runs(run)
        if tasks and all(status in FINAL for _, status, _, _ in tasks):
            break
        time.sleep(15)
    else:
        print(f"still running after {args.wait}s; check run {run} in the console")
        return 1
    _, status, message, task_run = tasks[0]
    # The first line says what went wrong; the rest of an AIDP task message is
    # SDK boilerplate -- timestamp, internal endpoint, troubleshooting links.
    first_line = ((message or "").strip().splitlines() or [""])[0]
    print(f"seed task: {status} -- {first_line}")
    if status != "SUCCESS":
        detail = readable_failure(client.task_output(task_run))
        if detail:
            print(detail[-1500:])
        return 1
    print(f"seeded: {inputs['uri']} and {inputs['claim_table']}. Run the demo job now.")
    return 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("migrated", help="the migrate output directory for the demo")
    parser.add_argument("--workspace-key")
    parser.add_argument("--cluster-key")
    parser.add_argument("--instance-id", default=None)
    parser.add_argument("--profile", default=None)
    parser.add_argument("--auth", default=None)
    parser.add_argument("--prefix", default="", help="workspace folder, as for publish")
    parser.add_argument("--workspace-root", default="/Workspace")
    parser.add_argument("--create-bucket", action="store_true")
    parser.add_argument("--compartment", help="compartment OCID for --create-bucket")
    parser.add_argument("--wait", type=int, default=900, help="seconds to wait for the run")
    parser.add_argument("--overwrite", action="store_true",
                        help="replace existing files at the path and an existing claim table")
    parser.add_argument("--dry-run", action="store_true",
                        help="print what would be done and write the notebook locally")
    args = parser.parse_args(argv)
    try:
        inputs = read_inputs(args.migrated)
        print(f"bucket   {inputs['bucket']}  (namespace {inputs['namespace']})")
        print(f"files    {inputs['uri']}  ({ROWS} rows, {len(POLICIES)} policies)")
        print(f"table    {inputs['claim_table']}  (migrated DDL, then {ROWS} rows)")
        if args.dry_run:
            out = Path(args.migrated) / SEED_NOTEBOOK
            out.write_text(seed_notebook(inputs, overwrite=args.overwrite), encoding="utf-8")
            print(f"dry run: wrote {out}; nothing was sent")
            return 0
        if not (args.workspace_key and args.cluster_key):
            raise SeedError("--workspace-key and --cluster-key are required (or --dry-run)")
        if args.create_bucket:
            if not args.compartment:
                raise SeedError("--create-bucket needs --compartment <ocid>")
            made = create_bucket(inputs, args.compartment, args.profile, args.auth)
            print("bucket created" if made == "created" else
                  "bucket already exists -- not created by this script; its existing "
                  "files are kept unless --overwrite")
        if args.overwrite:
            print(f"warning: --overwrite replaces the files at {inputs['uri']}. That "
                  f"bucket is the same for everyone running the demo in this "
                  f"tenancy -- the name comes from the Fabric path, not from you "
                  f"-- so this replaces their input too.")
        return run_seed(inputs, args)
    except SeedError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    except Exception as exc:  # AidpError, AidpUnavailable: one line, not a traceback
        from fabric_aidp.publish.aidp_client import AidpError, AidpUnavailable
        if not isinstance(exc, (AidpError, AidpUnavailable)):
            raise
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
