"""Generate a real, reviewable S3 → OCI Object Storage data-copy job.

We do NOT re-implement a byte-copy engine — that's a solved problem. Instead we
generate an [rclone](https://rclone.org) job: rclone has native backends for
both AWS S3 and OCI Object Storage, and gives parallel, resumable,
checksum-verified transfers for free.

Output is a self-contained shell script per bucket (source path + destination +
the exact rclone commands). Nothing moves until a human runs the script — which
keeps the project's "review before you trust" model, and means we're not on the
hook for maintaining a transfer engine.
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class Finding:
    rule: str
    detail: str
    severity: str

    def __str__(self) -> str:
        return f"[{self.severity}] {self.rule}: {self.detail}"


@dataclass
class TransferResult:
    source_sql: str        # reused by the report as the "before" block
    translated_sql: str    # reused by the report as the "after" block (the script)
    findings: list[Finding] = field(default_factory=list)

    @property
    def changes(self) -> int:
        return sum(1 for f in self.findings if f.severity == "rewrite")

    @property
    def flags(self) -> int:
        return sum(1 for f in self.findings if f.severity == "flag")

    @property
    def needs_manual_review(self) -> bool:
        return self.flags > 0


def build_transfer(
    bucket: str,
    oci_bucket: str,
    namespace: str,
    *,
    aws_region: str | None = None,
    oci_region: str = "us-ashburn-1",
    oci_profile: str = "DEFAULT",
    compartment_ocid: str = "<compartment-ocid>",
) -> TransferResult:
    aws_region = aws_region or "us-east-1"
    ns = namespace or "<your-oci-namespace>"

    script = f"""#!/usr/bin/env bash
# Copy s3://{bucket}  →  oci://{oci_bucket}@{ns}
# Generated by aws-aidp-migrator. Uses rclone (native S3 + OCI backends).
# Review, then run:  bash {bucket}.transfer.sh
set -euo pipefail

# --- rclone config (written to a temp file; no global config touched) ---
CONF="$(mktemp)"
cat > "$CONF" <<'RCLONE'
# awssrc uses env_auth: AWS_PROFILE / ~/.aws/credentials / IAM role
[awssrc]
type = s3
provider = AWS
env_auth = true
region = {aws_region}

[ocidest]
type = oracleobjectstorage
provider = user_principal_auth
namespace = {ns}
region = {oci_region}
compartment = {compartment_ocid}
config_file = ~/.oci/config
config_profile = {oci_profile}
RCLONE

# --- ensure the destination bucket exists, then copy ---
rclone --config "$CONF" mkdir "ocidest:{oci_bucket}" || true
rclone --config "$CONF" copy "awssrc:{bucket}" "ocidest:{oci_bucket}" \\
    --checksum --transfers 16 --fast-list --progress

rm -f "$CONF"
echo "done: s3://{bucket} -> oci://{oci_bucket}@{ns}"
"""

    findings = [
        Finding("rclone_transfer",
                f"Generated rclone copy job  s3://{bucket} → oci://{oci_bucket}@{ns} "
                "(parallel, resumable, checksum-verified — proven engine, not a custom copier)",
                "rewrite"),
        Finding("transfer_prereqs",
                "Before running: install rclone, set AWS creds (env/profile), and an "
                "~/.oci/config profile with a real compartment OCID.",
                "flag"),
    ]
    before = f"s3://{bucket}/   (AWS S3 bucket, {aws_region})"
    return TransferResult(source_sql=before, translated_sql=script, findings=findings)
